/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/external/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public availability; no client secrets or account information. */
        get: operations["getExternalProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/settings/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administrator only. Returns a secretConfigured flag, never the secret. */
        get: operations["getExternalGoogleSettings"];
        /** @description Administrator only. Saves encrypted client credentials and cancels pending OAuth flows. */
        put: operations["putExternalGoogleSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists only connections owned by the current Linux identity. */
        get: operations["getExternalConnections"];
        put?: never;
        post?: never;
        /** @description Requires current Linux password. Unlinks an owned identity and revokes all owner panel sessions. */
        delete: operations["unlinkExternalConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts browser-bound Google OIDC authorization through the fixed HTTPS relay. Linking also requires the existing panel session and current Linux password. */
        post: operations["startExternalGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/google/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires the HttpOnly flow cookie from start. Poll at most once every three seconds. Expiration, cancellation, restart or settings changes require a new flow. */
        post: operations["pollExternalGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external/google/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cancels the flow belonging to the browser cookie. */
        post: operations["cancelExternalGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Active panel sessions for the caller; administrators may select another user. */
        get: operations["getSessions"];
        put?: never;
        /** @description End an owned session, or another user's session as administrator. Requires the standard request-origin headers. */
        post: operations["endSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/security-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Latest 100 security events for the caller, or a selected user for administrators. */
        get: operations["getSecurityHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvatar"];
        /** @description Upload JPEG/PNG, at most 2 MiB and 4 megapixels. Stored as a 128px square JPEG. */
        put: operations["putAvatar"];
        post?: never;
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/avatar/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvatarImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallpaper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallpaper"];
        put: operations["putWallpaper"];
        post?: never;
        delete: operations["deleteWallpaper"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wallpaper/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallpaperImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreferences"];
        put: operations["putPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cooling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCooling"];
        put: operations["setCooling"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post: operations["updateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an authorized management snapshot
         * @description ManagementViews maps each core view to its response schema. Ordinary users are restricted to their own account/session/jobs and authorized module views. Domain validation errors use Error with HTTP 200 for compatibility. Unknown views never execute mutations.
         */
        get: {
            parameters: {
                query: {
                    /** @description Core views: job, jobs, accounts, account-details, account-sessions, homes, homes-check, sharing, share-folders, home-folders, mount-folders, modules, module-sources, module-catalog, web-access, system-updates, network, storage-options, raid-candidates, smart, services, journal, updates, nfs, power. Additional module queries require an enabled module. */
                    view: string;
                    target?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Selected core snapshot, module-owned JSON response, or domain error */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManagementJob"] | components["schemas"]["ManagementJob"][] | components["schemas"]["AccountInventory"] | components["schemas"]["ManagedAccount"] | components["schemas"]["SSHSession"][] | components["schemas"]["HomeLocations"] | components["schemas"]["HomePreflight"] | components["schemas"]["ShareInventory"] | components["schemas"]["FolderLocations"] | components["schemas"]["FolderLocations"] | components["schemas"]["FolderLocations"] | components["schemas"]["InstalledModules"] | components["schemas"]["ModuleSources"] | components["schemas"]["ModuleCatalog"] | components["schemas"]["WebAccess"] | components["schemas"]["SystemUpdates"] | components["schemas"]["NetworkView"] | components["schemas"]["StorageOptions"] | components["schemas"]["RaidCandidates"] | components["schemas"]["SmartReport"] | components["schemas"]["ServicesView"] | components["schemas"]["JournalView"] | components["schemas"]["PackageUpdates"] | components["schemas"]["NFSExports"] | components["schemas"]["PowerState"] | components["schemas"]["Error"] | {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description System handler or task journal unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Preview, submit, cancel, inspect or acknowledge an operation
         * @description plan requires action/params and returns OperationPlan or Error; run requires id/action/params/fingerprint/confirmation and returns JobAccepted. cancel/recover/acknowledge require id; clear-history accepts {}. Queued work is not replayed after restart. Cancellation is cooperative, never a kill request. IDs must be unique per logical submission; retry uncertain submissions with the same ID.
         */
        post: {
            parameters: {
                query: {
                    view: "plan" | "run" | "cancel" | "recover" | "acknowledge" | "clear-history";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManagementRequest"];
                };
            };
            responses: {
                /** @description Plan, existing job ID, recovery report, acknowledgement or domain error */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperationPlan"] | components["schemas"]["JobAccepted"] | components["schemas"]["JobRecovery"] | components["schemas"]["OperationOK"] | components["schemas"]["Error"];
                    };
                };
                /** @description Durably accepted job */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
                /** @description Invalid request or mode */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Access denied */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Stale state or task conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Queue full */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Handler or journal unavailable; reconcile by ID before retrying */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    hours?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One recorded sample per minute; gaps are retained */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Metrics"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Persistent alerts; an ordinary user receives an empty list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Dismiss resolved history for the caller; active warnings remain */
        delete: {
            parameters: {
                query?: {
                    /** @description Omit to dismiss all resolved history */
                    id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description History cleared */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin user PTY WebSocket; input/resize JSON in */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    target: string;
                    /** @description Return a bounded JPEG image thumbnail instead of the original file */
                    thumbnail?: "1";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File attachment or image/jpeg thumbnail under caller Linux UID/GID; no-store */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Access denied or thumbnail unavailable */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Thumbnail generation timed out or service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query: {
                    target: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Entire upload atomically published; existing files are never overwritten */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description File exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authenticated same-origin WebSocket invalidations
         * @description Server messages match EventEnvelope. Reread HTTP snapshots after resync/reconnect; there is no replay cursor. No commands are accepted. Slow clients disconnect; revoked sessions close with code 1008.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket established */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sign-in required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid origin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modules/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a module bundle for inspection before installation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Staged archive reference for module.install preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Administrator required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Agent unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/module-assets/{module}/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a manifest-listed UI asset from an enabled module */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    module: string;
                    /** @description Relative asset path */
                    asset: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset with its native content type and no-store policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Module disabled or asset not listed in its signed manifest */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ExternalGoogleSettings: {
            /** @constant */
            provider: "google";
            clientId: string;
            secretConfigured: boolean;
            enabled: boolean;
            redirectUri: string;
        };
        ExternalGoogleSettingsInput: {
            clientId: string;
            /** @description Empty preserves the existing secret only when the client ID is unchanged. */
            clientSecret: string;
            enabled: boolean;
        };
        ExternalConnection: {
            id: string;
            provider: string;
            email: string;
            name: string;
            created: number;
        };
        ExternalStart: {
            /** @enum {string} */
            purpose: "login" | "link";
            /** @description Current Linux password required for linking; never sent to the gateway. */
            password?: string;
        };
        ExternalAuthorization: {
            url: string;
            expiresIn: number;
        };
        ExternalFlowStatus: {
            /** @enum {string} */
            status: "pending" | "linked" | "authenticated";
        };
        ExternalProviders: {
            google: {
                enabled: boolean;
            };
        };
        ExternalUnlink: {
            id: string;
            password: string;
        };
        JobRecovery: {
            message: string;
            checks: {
                label: string;
                value: unknown;
            }[];
            route: string;
            /** @description An explicit action requiring a fresh preview and confirmation */
            recoveryAction?: string | null;
        };
        ManagementJob: {
            id: string;
            user: string;
            action: string;
            target: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
            stage: string;
            created: string;
            updated: string;
            result: {
                [key: string]: unknown;
            };
            /** @description Cancellation is currently supported at a safe checkpoint */
            canCancel: boolean;
            cancelRequested: boolean;
            /** @description Unreviewed terminal tasks are retained when history is cleared */
            needsReview: boolean;
            recovery?: components["schemas"]["JobRecovery"];
        };
        Identity: {
            username: string;
            name: string;
            uid: number;
            role: string;
            /** @description Linux login succeeded but Samba password synchronization needs attention. */
            smbSyncWarning?: boolean;
        };
        User: {
            username: string;
            name: string;
            uid: number;
            gid: number;
            home: string;
            shell: string;
            category: string;
            groups: string[];
        };
        Group: {
            name: string;
            gid: number;
            members: string[];
        };
        PanelSession: {
            id: string;
            user: string;
            address: string;
            device: string;
            /** @description Unix timestamp in seconds */
            created: number;
            expires: number;
            current: boolean;
            /** @constant */
            kind: "panel";
        };
        AccountEvent: {
            user: string;
            actor: string;
            action: string;
            result: string;
            /** Format: date-time */
            created: string;
        };
        Accounts: {
            users: components["schemas"]["User"][];
            groups: components["schemas"]["Group"][];
        };
        Metrics: {
            systemTotal: number;
            systemAvailable: number;
            disks: {
                [key: string]: {
                    read: number;
                    write: number;
                };
            };
            network: {
                [key: string]: {
                    read: number;
                    write: number;
                };
            };
            hostname: string;
            cpu: number | null;
            memoryTotal: number;
            memoryUsed: number;
            uptime: number;
            cpuTemperature: number | null;
            observedAt: string;
            /** @description Fan PWM duty as a percentage; null when unavailable. */
            cpuFanPercent?: number | null;
            cpuFanRpm: number | null;
        };
        Array: {
            missing?: number;
            memberStates?: {
                [key: string]: string;
            };
            reshapePending?: boolean;
            syncPercent?: number;
            syncSpeed?: number;
            syncRemaining?: number;
            name: string;
            level: string;
            state: string;
            degraded: string;
            members: string[];
            sync: string;
            progress: string;
            device: string;
            uuid: string;
            size: number;
        };
        Preferences: {
            /**
             * @description Personal interface language; English is the default and fallback.
             * @default en
             * @enum {string}
             */
            language: "en" | "ru" | "uk";
            taskbar?: string[];
            desktopLayouts?: {
                [key: string]: {
                    id: string;
                    kind: string;
                    x: number;
                    y: number;
                }[];
            };
            smartCrcBaselines?: {
                [key: string]: number;
            };
            /** @enum {string} */
            theme: "dark" | "light";
            layouts: {
                [key: string]: string[];
            };
        };
        Login: {
            username: string;
            password: string;
            /** @description Required only after a 409 password-change-required response. */
            newPassword?: string;
        };
        Error: {
            error: string;
        };
        Health: {
            status: string;
            version: string;
        };
        Device: {
            name: string;
            kname: string;
            path: string;
            type: string;
            size: number;
            model?: string | null;
            serial?: string | null;
            tran?: string | null;
            fstype?: string | null;
            uuid?: string | null;
            pkname?: string | null;
            rota?: boolean;
            mountpoints?: (string | null)[];
            children?: components["schemas"]["Device"][];
            start?: number;
            label?: string | null;
        };
        Mount: {
            source: string;
            target: string;
            fstype: string;
            options: string;
            children?: components["schemas"]["Mount"][];
            size?: number | null;
            used?: number | null;
            avail?: number | null;
        };
        Storage: {
            devices: components["schemas"]["Device"][];
            mounts: components["schemas"]["Mount"][];
            arrays: components["schemas"]["Array"][];
            observedAt: string;
        };
        CoolingSettings: {
            /** @enum {string} */
            profile: "quiet" | "balanced" | "performance";
            sampleSeconds: number;
            /** @enum {string} */
            cpuProfile: "quiet" | "balanced" | "performance";
        };
        CoolingState: {
            config: components["schemas"]["CoolingSettings"];
            available: boolean;
            status: {
                profile: string;
                dutyPercent: number;
                reason: string;
                observedAt: number;
                disks: {
                    path: string;
                    /** @enum {string} */
                    state: "active" | "sleeping" | "unknown" | "unavailable";
                    temperature: number | null;
                    device?: string;
                    /** @enum {string} */
                    health?: "passed" | "warning" | "failed" | "unknown";
                    stale?: boolean;
                    observedAt?: number | null;
                    warnings?: string[];
                    attributes?: {
                        id: number;
                        name: string;
                        raw?: {
                            value?: number;
                            string?: string;
                        };
                    }[];
                }[];
                cpu?: {
                    available: boolean;
                    profile?: string;
                    thresholds?: number[];
                };
            };
        };
        Profile: {
            /** @enum {string} */
            role: "admin" | "user";
            username: string;
            name: string;
            uid: string;
            home: string;
            groups: string[];
            keys: {
                id: string;
                type: string;
                fingerprint: string;
                comment: string;
            }[];
        };
        ProfileUpdate: {
            /** @enum {string} */
            action: "name" | "password" | "add" | "delete";
            name?: string;
            currentPassword?: string;
            newPassword?: string;
            key?: string;
            id?: string;
        };
        ManagementRequest: {
            id?: string;
            action?: string;
            /** @description Action-specific parameters validated by the owning core component or installed module. Secrets are never persisted in the job journal. */
            params?: {
                [key: string]: unknown;
            };
            fingerprint?: string;
            confirmation?: string;
        };
        OperationPlan: {
            target: string;
            details: string[];
            fingerprint: string;
            confirmation: string;
        };
        JobAccepted: {
            id: string;
        };
        OperationOK: {
            /** @constant */
            ok: true;
        };
        HomeLocations: {
            path: string;
            users: {
                name: string;
                home: string;
            }[];
            recovery: boolean;
        };
        HomeBlocker: {
            title: string;
            kind: string;
            user: string;
            unit: string;
            reason: string;
            processes: {
                name: string;
                pid: number;
            }[];
        };
        HomePreflight: components["schemas"]["OperationPlan"] | {
            blockers: components["schemas"]["HomeBlocker"][];
        };
        FolderEntry: {
            name: string;
            path: string;
            reason?: string;
        };
        FolderLocations: {
            roots: (string | components["schemas"]["FolderEntry"])[];
            path: string;
            folders: components["schemas"]["FolderEntry"][];
        };
        SSHSession: {
            id: string;
            user: string;
            uid: string | null;
            kind: string;
            address: string;
            leader: string | null;
            state: string | null;
            created: string | null;
        };
        ManagedAccount: {
            username: string;
            name: string;
            home: string;
            shell: string;
            category: string;
            primaryGroup: string;
            expiry: string;
            reason: string;
            passwordStatus?: string;
            uid: number;
            gid: number;
            minDays?: number;
            maxDays?: number;
            warnDays?: number;
            inactiveDays?: number;
            expiryDay?: number;
            panel: boolean;
            disabled: boolean;
            expired: boolean;
            ssh: boolean;
            forcePasswordChange?: boolean;
            groups: string[];
            keys?: {
                id: string;
                type: string;
                fingerprint: string;
                comment: string;
            }[];
            keysError?: string;
            smb?: {
                enabled: boolean;
                status: string;
            };
        };
        ManagedGroup: {
            name: string;
            gid: number;
            members: string[];
            primaryMembers: string[];
            editable: boolean;
            system: boolean;
        };
        AccountInventory: {
            users: components["schemas"]["ManagedAccount"][];
            groups: components["schemas"]["ManagedGroup"][];
            shells: string[];
            passwordPolicy: string;
            sshAvailable: boolean;
        };
        SharedFolder: {
            name: string;
            path: string;
            smb: boolean;
            nfs: boolean;
            readOnly: boolean;
            readers: string[];
            writers: string[];
            clients: string[];
        };
        ShareInventory: {
            shares: components["schemas"]["SharedFolder"][];
            accounts: {
                [key: string]: {
                    enabled: boolean;
                    status: string;
                    uid: number;
                };
            };
            drift: boolean;
            recovery: boolean;
            smbAvailable: boolean;
            services: {
                [key: string]: string;
            };
            /** @description Redacted smbstatus JSON; fields depend on the installed Samba version. */
            sessions: {
                [key: string]: unknown;
            };
        };
        NFSExports: {
            exports: {
                path: string;
                clients: string[];
                readOnly: boolean;
            }[];
        };
        ModuleManifest: {
            id: string;
            title: string;
            version: string;
            signer: string;
            core: string;
            enabled: boolean;
            description?: string;
            dependencies?: {
                [key: string]: string;
            };
            packages?: {
                [key: string]: string;
            };
            requiredBy: string[];
            files: {
                [key: string]: string;
            };
            translations?: {
                [key: string]: {
                    title: string;
                    description?: string;
                };
            };
        };
        InstalledModules: {
            core: string;
            api: number;
            installed: components["schemas"]["ModuleManifest"][];
        };
        AvailableModule: components["schemas"]["ModuleManifest"] & {
            reason: string;
            updateAvailable: boolean;
            repository: string;
        };
        ModuleCatalog: {
            available: components["schemas"]["AvailableModule"][];
            errors: {
                repository: string;
                error: string;
            }[];
        };
        ModuleSource: {
            id: string;
            url: string;
            official: boolean;
            fingerprint?: string;
            signers: string[];
        };
        ModuleSources: {
            sources: components["schemas"]["ModuleSource"][];
        };
        WebAccess: {
            port: number;
            pending: boolean;
            error: string;
        };
        PowerState: {
            throttled: string;
            undervoltage: boolean;
            throttling: boolean;
            pastUndervoltage: boolean;
        };
        ServicesView: {
            services: {
                unit: string;
                load?: string;
                active?: string;
                sub?: string;
                description?: string;
                enabled: string;
            }[];
        };
        JournalView: {
            entries: {
                time: string | null;
                priority: string | null;
                unit: string | null;
                message: string;
            }[];
        };
        PackageUpdates: {
            packages: string[];
            packageDetails: {
                name: string;
                installed: string;
                available: string;
                source: string;
                action: string;
            }[];
            rebootRequired: boolean;
        };
        UpdateSettings: {
            /** @enum {string} */
            channel: "stable" | "testing";
            /** @enum {string} */
            mode: "notify" | "download" | "auto";
            hour: number;
        };
        UpdateState: {
            operation?: string;
            id?: string;
            phase?: string;
            error?: string;
            version?: string | null;
            startedAt?: string;
            finishedAt?: string;
        };
        UpdateRelease: {
            version: string;
            run?: string;
            createdAt?: string;
        };
        SystemUpdates: {
            settings: components["schemas"]["UpdateSettings"];
            installed: {
                [key: string]: string;
            };
            candidate: components["schemas"]["UpdateRelease"] | null;
            checkedAt: string | null;
            available: boolean;
            busy: boolean;
            rollbackAvailable: boolean;
            state: components["schemas"]["UpdateState"];
            history: components["schemas"]["UpdateState"][];
        };
        IPConfig: {
            method: string;
            addresses: string[];
            gateway: string;
            dns: string[];
            ignoreAutoDns: boolean;
            neverDefault: boolean;
            metric: number;
            routes: {
                destination: string;
                gateway: string;
                metric: number;
            }[];
        };
        InterfaceConfig: {
            ipv4: components["schemas"]["IPConfig"];
            ipv6: components["schemas"]["IPConfig"];
            mtu: number;
        };
        WifiNetwork: {
            id: string;
            ssid: string;
            ssidHex: string;
            security: string;
            signal: number;
            frequency: number;
        };
        WifiInterface: {
            enabled?: boolean;
            hardwareEnabled?: boolean;
            mode?: number;
            clients?: number;
            networks: components["schemas"]["WifiNetwork"][];
            saved: {
                uuid: string;
                name: string;
                ssid: string;
            }[];
            activeAP: string;
        };
        WifiRadio: {
            present: boolean;
            enabled: boolean;
            hardwareEnabled: boolean;
        };
        NetworkInterface: {
            name: string;
            kind: string;
            mac: string;
            state: string;
            profile: string;
            uuid?: string;
            index: number;
            mtu: number;
            nmState?: number;
            adminUp: boolean;
            carrier?: boolean;
            managed?: boolean;
            editable: boolean;
            addresses: string[];
            dns: string[];
            config: components["schemas"]["InterfaceConfig"] | null;
            wifi?: components["schemas"]["WifiInterface"];
            sharingGroup?: string | null;
            sharing?: {
                available: boolean;
                ap: boolean;
                bands: string[];
                channels?: {
                    [key: string]: number[];
                };
                phy?: string;
                concurrent?: boolean;
            };
        };
        NetworkShareGroup: {
            id: string;
            name: string;
            source: string;
            outputs: string[];
            /** @enum {string} */
            mode: "bridge" | "nat";
            wifi: {
                [key: string]: {
                    ssid: string;
                    band: string;
                    channel?: number;
                };
            };
            enabled: boolean;
            autostart: boolean;
            bridge: string;
            /** @enum {string} */
            status: "active" | "stopped" | "upstream" | "error";
            addresses: string[];
        };
        NetworkView: {
            backend: string;
            interfaces: components["schemas"]["NetworkInterface"][];
            routes: {
                family: number;
                dst?: string;
                gateway?: string;
                dev?: string;
                metric?: number;
                table?: string | number;
                protocol?: string;
                type?: string;
            }[];
            change: {
                id: string;
                interface: string;
                user: string;
                status: string;
                deadline: number;
                addresses: string[];
            } | null;
            serverTime: number;
            timeout: number;
            wifi: components["schemas"]["WifiRadio"] | null;
            sharing: {
                groups: components["schemas"]["NetworkShareGroup"][];
                ready: boolean;
            };
        };
        SmartSchedule: {
            test: string;
            weekday: number;
            hour: number;
            weeks?: number;
            startDate?: string;
        };
        MediaInfo: {
            kind: string;
            readOnly: boolean;
            name?: string;
            manufacturerId?: string;
            manufactured?: string;
            revision?: string;
            usbId?: string;
            usbVersion?: string;
            linkMbps?: string;
            manufacturer?: string;
        };
        StorageOptionDevice: {
            path: string;
            kname: string;
            type?: string;
            size?: number;
            fstype?: string | null;
            uuid?: string | null;
            mountpoints?: (string | null)[];
            smartSchedules?: components["schemas"]["SmartSchedule"][];
            smartSchedule?: components["schemas"]["SmartSchedule"] | null;
            media?: components["schemas"]["MediaInfo"];
            mountSettings?: {
                point: string;
                automount: boolean;
                readOnly: boolean;
            } | null;
            protectedReason: string;
            busyReason: string;
            raidReason: string;
            raidEligible: boolean;
            ejectable: boolean;
            filesystemHealth?: {
                [key: string]: unknown;
            } | null;
        };
        StorageOptions: {
            sleepSettings: {
                minutes: number;
            };
            sleepStatus: {
                [key: string]: {
                    device: string;
                    minutes: number | null;
                    status: string;
                    error?: string;
                };
            };
            devices: components["schemas"]["StorageOptionDevice"][];
            formats: string[];
            capabilities: {
                [key: string]: {
                    create: boolean;
                    grow: boolean;
                    shrink: boolean;
                    resizeRequiresMount?: boolean;
                    resizeRequiresUnmount?: boolean;
                };
            };
        };
        RaidCandidates: {
            devices: {
                path: string;
                kname: string;
                type: string;
                size: number;
            }[];
        };
        /** @description Native smartctl JSON report, versioned by smartctl (json_format_version). Keys vary by SATA/NVMe/USB support; absence is not health success. */
        SmartReport: {
            json_format_version: number[];
            smartctl: {
                [key: string]: unknown;
            };
            device?: {
                [key: string]: unknown;
            };
            temperature?: {
                current?: number;
            };
            smart_status?: {
                passed?: boolean;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Query-name to response-schema map. Each GET response is the value for the selected view, not this mapping object. Installed modules own additional query contracts. */
        ManagementViews: {
            job?: components["schemas"]["ManagementJob"];
            jobs?: components["schemas"]["ManagementJob"][];
            accounts?: components["schemas"]["AccountInventory"];
            "account-details"?: components["schemas"]["ManagedAccount"];
            "account-sessions"?: components["schemas"]["SSHSession"][];
            homes?: components["schemas"]["HomeLocations"];
            "homes-check"?: components["schemas"]["HomePreflight"];
            sharing?: components["schemas"]["ShareInventory"];
            "share-folders"?: components["schemas"]["FolderLocations"];
            "home-folders"?: components["schemas"]["FolderLocations"];
            "mount-folders"?: components["schemas"]["FolderLocations"];
            modules?: components["schemas"]["InstalledModules"];
            "module-sources"?: components["schemas"]["ModuleSources"];
            "module-catalog"?: components["schemas"]["ModuleCatalog"];
            "web-access"?: components["schemas"]["WebAccess"];
            "system-updates"?: components["schemas"]["SystemUpdates"];
            network?: components["schemas"]["NetworkView"];
            "storage-options"?: components["schemas"]["StorageOptions"];
            "raid-candidates"?: components["schemas"]["RaidCandidates"];
            smart?: components["schemas"]["SmartReport"];
            services?: components["schemas"]["ServicesView"];
            journal?: components["schemas"]["JournalView"];
            updates?: components["schemas"]["PackageUpdates"];
            nfs?: components["schemas"]["NFSExports"];
            power?: components["schemas"]["PowerState"];
        };
        Notification: {
            id: string;
            message: string;
            /** @enum {string} */
            severity: "info" | "success" | "warning" | "error";
            active: boolean;
            created: string;
            updated: string;
        };
        EventEnvelope: {
            /** @constant */
            version: 1;
            /** @enum {unknown} */
            type: "resync" | "storage.changed" | "jobs.changed" | "notifications.changed" | "cooling.unavailable" | "metrics.unavailable";
            data: null;
        } | {
            /** @constant */
            version: 1;
            /** @constant */
            type: "metrics";
            data: components["schemas"]["Metrics"];
        } | {
            /** @constant */
            version: 1;
            /** @constant */
            type: "cooling";
            data: components["schemas"]["CoolingState"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getExternalProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalProviders"];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getExternalGoogleSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalGoogleSettings"];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putExternalGoogleSettings: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalGoogleSettingsInput"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalGoogleSettings"];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getExternalConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalConnection"][];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unlinkExternalConnection: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalUnlink"];
            };
        };
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    startExternalGoogle: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalStart"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAuthorization"];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    pollExternalGoogle: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalFlowStatus"];
                };
            };
            /** @description Authorization still pending */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalFlowStatus"];
                };
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelExternalGoogle: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failure; external.* error codes describe authorization failures. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postLogin: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: {
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions, with opaque public IDs and no session tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PanelSession"][];
                };
            };
        };
    };
    endSession: {
        parameters: {
            query?: {
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            /** @description Session ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Another user's session is not accessible */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session already ended */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSecurityHistory: {
        parameters: {
            query?: {
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account history without credentials or key material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEvent"][];
                };
            };
        };
    };
    getAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's avatar version, empty when absent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: string;
                    };
                };
            };
        };
    };
    putAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Avatar saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid image */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own avatar removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAvatarImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's avatar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description No avatar */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accounts"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Storage"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWallpaper: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current wallpaper revision, empty when unset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                    };
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putWallpaper: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
            };
        };
        responses: {
            /** @description Current wallpaper revision, empty when unset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                    };
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteWallpaper: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current wallpaper revision, empty when unset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: string;
                    };
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWallpaperImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's wallpaper */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description No wallpaper */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    putPreferences: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    postLogout: {
        parameters: {
            query?: never;
            header: {
                "X-PaNasMs-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCooling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cooling settings and last observed controller state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoolingState"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setCooling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoolingSettings"];
            };
        };
        responses: {
            /** @description Cooling settings and last observed controller state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoolingState"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own Linux profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated; password change revokes panel sessions */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failure */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
