name: Build PaNasMs
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: PaNasMs/panasms/.github/workflows/build.yml@4d8531a765beb651d779ed817d2eca2e159932ec
    with:
      build_ref: 4d8531a765beb651d779ed817d2eca2e159932ec
      frontend_ref: ${{ github.sha }}
