name: Build PaNasMs
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: PaNasMs/panasms/.github/workflows/build.yml@e18160ceb675dfdb81f7d5b5673982e5026cc3bc
    with:
      build_ref: e18160ceb675dfdb81f7d5b5673982e5026cc3bc
      frontend_ref: ${{ github.sha }}
